#!/usr/bin/env bash
# setup-clients.sh - Register OAuth clients for every example app against the
# isolated betterbase-e2e stack (accounts on localhost:25377) and write the
# client IDs to e2e/.env.e2e for playwright.config.ts.
#
# Idempotent: existing clients (matched by name) are reused, so this is safe
# to run before every test invocation.
#
# Prerequisites:
#   - The betterbase-e2e compose stack must be up (betterbase-dev: `just e2e-up`)
#   - Root .env of the betterbase-dev checkout must exist (DB credentials)
#
# BB_DEV_ROOT defaults to the standard layout (this repo checked out as
# betterbase-dev/betterbase-examples); override for other layouts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.e2e"
BB_DEV_ROOT="${BB_DEV_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
ROOT_ENV="$BB_DEV_ROOT/.env"
ACCOUNTS_CONTAINER="${ACCOUNTS_CONTAINER:-betterbase-e2e-accounts-1}"
ACCOUNTS_PORT="${ACCOUNTS_PORT:-25377}"

if [ ! -f "$ROOT_ENV" ]; then
    echo "Error: $ROOT_ENV not found (set BB_DEV_ROOT to the betterbase-dev checkout)" >&2
    exit 1
fi

if ! docker exec "$ACCOUNTS_CONTAINER" test -f /app/oauth-client >/dev/null 2>&1; then
    echo "Error: $ACCOUNTS_CONTAINER not running or missing /app/oauth-client." >&2
    echo "Start the e2e stack first: cd $BB_DEV_ROOT && just e2e-up" >&2
    exit 1
fi

# DB credentials come from the same root .env the e2e compose project uses.
set -a; source "$ROOT_ENV"; set +a
DB_USER="${ACCOUNTS_DB_USER:-accounts}"
DB_PASS="${ACCOUNTS_DB_PASSWORD:-accounts}"
DB_NAME="${ACCOUNTS_DB_NAME:-accounts}"

# appname:port:scopes (scopes are space-separated; photos needs files)
APPS=(
    "tasks:25391:sync"
    "notes:25392:sync"
    "photos:25393:sync files"
    "board:25394:sync"
    "chat:25395:sync"
    "passwords:25396:sync"
)

oauth_client() {
    docker exec "$ACCOUNTS_CONTAINER" sh -c \
        "DATABASE_URL='postgres://$DB_USER:$DB_PASS@accounts-db:5432/$DB_NAME?sslmode=disable' /app/oauth-client $*"
}

# list output prints "ID: <id>" then "Name: <name>" pairs
client_id_by_name() {
    oauth_client list 2>/dev/null | awk -v n="$1" \
        '$1 == "ID:" { id = $2 } $1 == "Name:" && $2 == n { print id }' | head -1
}

echo "# Generated by scripts/setup-clients.sh — client IDs for the e2e app servers." > "$ENV_FILE"
echo "ACCOUNTS_HOST=localhost:$ACCOUNTS_PORT" >> "$ENV_FILE"

for entry in "${APPS[@]}"; do
    app="${entry%%:*}"
    rest="${entry#*:}"
    port="${rest%%:*}"
    scopes="${rest#*:}"
    name="${app}-e2e"

    client_id="$(client_id_by_name "$name" || true)"
    if [ -z "$client_id" ]; then
        echo "Creating OAuth client $name (http://localhost:$port/)..."
        scope_args=""
        for s in $scopes; do scope_args="$scope_args --scope $s"; done
        # shellcheck disable=SC2086
        output="$(oauth_client create --name "$name" --redirect-uri "http://localhost:$port/" $scope_args 2>&1)" || {
            echo "Error: failed to create client for $app:" >&2
            echo "$output" >&2
            exit 1
        }
        client_id="$(echo "$output" | grep '^Client ID:' | awk '{print $3}')"
    else
        echo "Reusing OAuth client $name ($client_id)"
    fi

    if [ -z "$client_id" ]; then
        echo "Error: could not determine client ID for $app" >&2
        exit 1
    fi

    upper="$(echo "$app" | tr '[:lower:]-' '[:upper:]_')"
    echo "${upper}_CLIENT_ID=$client_id" >> "$ENV_FILE"
done

echo "Wrote $ENV_FILE"
